# Generated by Django 5.1.6 on 2025-04-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_bridgeinventory_id_alter_code_an_parameters_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='class_field',
            field=models.CharField(db_column='class', max_length=255),
        ),
    ]
