# Generated by Django 5.1.6 on 2025-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_link_class_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=50)),
                ('selected_province', models.CharField(db_column='selectedProvince', max_length=100)),
                ('selected_kabupaten', models.CharField(blank=True, db_column='selectedKabupaten', max_length=100, null=True)),
                ('lg_name', models.CharField(db_column='lgName', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('phone', models.CharField(db_column='phone', max_length=20)),
            ],
            options={
                'verbose_name': 'Form Data',
                'verbose_name_plural': 'Form Data',
                'db_table': 'form_data',
            },
        ),
    ]
