from django.db import models

# Create your models here.

from models.bridge_inventory import BridgeInventory
from models.code_an_parameters import CODE_AN_Parameters
from models.code_an_unit_costs_per import CODE_AN_UnitCostsPER
from models.code_an_unit_costs_per_unpaved import CODE_AN_UnitCostsPERUnpaved
from models.code_an_unit_costs_reh import CODE_AN_UnitCostsREH
from models.code_an_unit_costs_rigid import CODE_AN_UnitCostsRIGID
from models.code_an_unit_costs_rm import CODE_AN_UnitCostsRM
from models.code_an_unit_costs_upg_unpaved import CODE_AN_UnitCostsUPGUnpaved
from models.code_an_unit_costs_widening import CODE_AN_UnitCostsWidening
from models.code_an_width_standards import CODE_AN_WidthStandards
from models.culvert_condition import CulvertCondition
from models.culvert_inventory import CulvertInventory
from models.form_data import FormData
from models.link import Link
from models.retaining_wall_condition import RetainingWallCondition
from models.retaining_wall_inventory import RetainingWallInventory
from models.road_condition import RoadCondition
from models.road_inventory import RoadInventory
from models.traffic_volume import TrafficVolume